-
  name: Nodejs Mysql terraform playbook
  hosts: localhost
  connection: local
  vars:
    project_dir: "{{ playbook_dir }}"

  tasks:
    - name: Include vars from file
      include_vars:
        file: terraform_vars.yaml

    - name: init
      command: "terraform init {{ project_dir }}"
      register: init_result

    - debug:
        var: init_result.stdout_lines

    - name: plan
      terraform:
        variables:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key}}"
          aws_region: "{{ aws_region }}"
          mysql_port: "{{ mysql_port }}"
        project_path: "{{ project_dir }}"
        plan_file: "{{ project_dir }}/plan.tfplan"
        state: planned
      register: plan_result

    - debug:
        var: plan_result.stdout_lines

    - name: apply
      terraform:
        variables:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key}}"
          aws_region: "{{ aws_region }}"
          mysql_port: "{{ mysql_port }}"
        project_path: "{{ project_dir }}"
        project_path: "{{ project_dir }}"
        plan_file: "{{ project_dir }}/plan.tfplan"
        state: present
      register: apply_result

    - debug:
       var: apply_result.stdout_lines
