-
  name: Nodejs Mysql terraform playbook
  hosts: localhost
  connection: local

  tasks:
    - name: Include vars from file
      include_vars:
        file: terraform_vars.yaml

    - name: init
      command: "terraform init {{ playbook_dir }}"
      register: init_output

    - debug:
        var: init_output.stdout_lines

    - name: Terraform plan
      terraform:
        variables:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key}}"
          aws_region: "{{ aws_region }}"
          mysql_port: "{{ mysql_port }}"
        project_path: "{{ playbook_dir }}"
        plan_file: "{{ playbook_dir }}/plan.tfplan"
        state: "{{ action }}"
      register: terraform_output

    - debug:
        var: terraform_output.stdout_lines
