-
  name: Nodejs Mysql terraform playbook
  hosts: localhost
  connection: local

  tasks:
    - name: Include vars from terraform_vars file
      include_vars:
        file: terraform_vars.yaml

    - name: Init nodejs-mysql app
      command: "terraform init {{ playbook_dir }}"

    - name: Nodejs-mysql app
      terraform:
        variables:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key}}"
          aws_region: "{{ aws_region }}"
          private_key_path: "{{ private_key_path }}"
          key_name: "{{ key_name }}"
          mysql_port: "{{ mysql_port }}"
          rds_instance_type: "{{ rds_instance_type }}"
          skip_final_snapshot: "{{ skip_final_snapshot }}"
          apply_immediately: "{{ apply_immediately }}"
          storage_type: "{{ storage_type }}"
          rds_identifier: "{{ rds_identifier }}"
          multi_az: "{{ multi_az }}"
          snapshot_identifier: "{{ snapshot_identifier }}"
          rds_storage: "{{ rds_storage }}"
          publicly_accessible: "{{ publicly_accessible }}"
          storage_encrypted: "{{ storage_encrypted }}"
          database: "{{ database }}"
          username: "{{ username }}"
          password: "{{ password }}"
          ec2_instance_ami_id: "{{ ec2_instance_ami_id }}"
          ec2_instance_type: "{{ ec2_instance_type }}"
          ec2_user: "{{ ec2_user }}"
        project_path: "{{ playbook_dir }}"
        plan_file: "{{ project_dir }}/plan.tfplan"
        state: "{{ input_state }}"
      register: terraform_output

    - debug:
        var: terraform_output.stdout_lines
